using System.IO;
using System.Collections.Generic;
using System.Linq;

namespace CodeGen
{
    /// <summary> Rust TSS code generator </summary>
    class CGenRust : CodeGenBase
    {
        protected override void WriteComment(string comment, bool addNewLine = true)
        {
            Write("// " + comment);
            if (addNewLine)
            {
                Write("\n");
            }
        }
        public CGenRust(string rootDir) : base(rootDir + @"src\", "TpmExtensions.rs.snips") {}

        void WriteAutoGeneratedSourceHeader()
        {
            TpmNamedConstant ver = TpmTypes.LookupConstant("TPM_SPEC_VERSION");
            Write("//\n" +
                  "// Copyright (c) Microsoft Corporation. All rights reserved.\n" +
                  "// Licensed under the MIT License. See the LICENSE file in the project root for full license information.\n" +
                  "//\n\n" +
                  "// This file is automatically generated from the TPM 2.0 rev. " +
                  (ver.NumericValue / 100.0).ToString("0.00") + " specification documents.\n" +
                  "// Do not edit it directly.\n");
        }

        internal override void Generate()
        {
            WriteAutoGeneratedSourceHeader();
            Write("use crate::tpm_structure::*;");
            Write("use crate::tpm_enum::*;");
            Write("");

            // Generate enums
            foreach (var e in TpmTypes.Get<TpmEnum>())
                GenEnum(e);
            foreach (var b in TpmTypes.Get<TpmBitfield>())
                GenBitfield(b);

            Write("use crate::crypt::*;\n");

            // Generate unions and structures
            GenUnions();
            foreach (var s in TpmTypes.Get<TpmStruct>())
                GenStruct(s);

            File.WriteAllText(RootDir + "tpm_types.rs", GeneratedCode.ToString());
            GeneratedCode.Clear();

            // Generate TPM methods
            GenCommands();
            File.WriteAllText(RootDir + "tpm.rs", GeneratedCode.ToString());
            GeneratedCode.Clear();
        }

        void GenEnum(TpmEnum e)
        {
            Write($"#[derive(Debug, Clone, Copy, PartialEq, Eq)]");
            Write($"pub enum {e.Name} {{");
            foreach (var v in e.Members)
            {
                Write($"    {v.Name} = {v.Value},");
            }
            Write("}");
        }

        void GenBitfield(TpmBitfield bf)
        {
            Write($"#[derive(Debug, Clone, Copy, PartialEq, Eq)]");
            Write($"pub struct {bf.Name} {{");
            foreach (var v in GetBifieldElements(bf)) // Assuming 'Members' is the correct property to retrieve members
            {
                Write($"    pub const {v.Name}: u32 = {v.Value};");
            }
            Write("}");
        }

        void GenUnions()
        {
            Write("pub trait TpmUnion {");
            Write("    fn get_union_selector(&self) -> u32;");
            Write("}");

            foreach (var u in TpmTypes.Get<TpmUnion>())
            {
                Write($"pub struct {u.Name};");
                Write($"impl TpmUnion for {u.Name} {{");
                Write("    fn get_union_selector(&self) -> u32 {");
                Write("        unimplemented!();");
                Write("    }");
                Write("}");
            }
        }

        void GenStruct(TpmStruct s)
        {
            Write($"#[derive(Debug, Clone)]");
            Write($"pub struct {s.Name} {{");
            foreach (var f in s.Fields)
            {
                Write($"    pub {f.Name}: {f.TypeName},");
            }
            Write("}");

            Write($"impl {s.Name} {{");
            Write($"    pub fn new() -> Self {{");
            Write($"        {s.Name} {{");
            foreach (var f in s.Fields)
            {
                Write($"            {f.Name}: Default::default(),");
            }
            Write("        }");
            Write("    }");
            Write("}");
        }

        void GenCommands()
        {
            WriteAutoGeneratedSourceHeader();
            Write("use crate::tpm_base::*;\n");

            Write("pub struct Tpm;");
            Write("impl Tpm {");
            foreach (var req in TpmTypes.Get<TpmStruct>().Where(s => s.Info.IsRequest()))
            {
                GenCommand(req);
            }
            Write("}");
        }

        void GenCommand(TpmStruct req)
        {
            var resp = GetRespStruct(req);
            var cmdName = GetCommandName(req);
            Write($"    pub fn {cmdName}(&self, req: {req.Name}) -> {resp.Name} {{");
            Write($"        unimplemented!();");
            Write("    }");
        }
    }
}