//
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See the LICENSE file in the project root for full license information.
//

// This file is automatically generated from the TPM 2.0 rev. 1.62 specification documents.
// Do not edit it directly.

use crate::tpm_base::*;

pub struct Tpm;
impl Tpm {
    pub fn Startup(&self, req: TPM2_Startup_REQUEST) -> StartupResponse {
        unimplemented!();
    }
    pub fn Shutdown(&self, req: TPM2_Shutdown_REQUEST) -> ShutdownResponse {
        unimplemented!();
    }
    pub fn SelfTest(&self, req: TPM2_SelfTest_REQUEST) -> SelfTestResponse {
        unimplemented!();
    }
    pub fn IncrementalSelfTest(&self, req: TPM2_IncrementalSelfTest_REQUEST) -> IncrementalSelfTestResponse {
        unimplemented!();
    }
    pub fn GetTestResult(&self, req: TPM2_GetTestResult_REQUEST) -> GetTestResultResponse {
        unimplemented!();
    }
    pub fn StartAuthSession(&self, req: TPM2_StartAuthSession_REQUEST) -> StartAuthSessionResponse {
        unimplemented!();
    }
    pub fn PolicyRestart(&self, req: TPM2_PolicyRestart_REQUEST) -> PolicyRestartResponse {
        unimplemented!();
    }
    pub fn Create(&self, req: TPM2_Create_REQUEST) -> CreateResponse {
        unimplemented!();
    }
    pub fn Load(&self, req: TPM2_Load_REQUEST) -> LoadResponse {
        unimplemented!();
    }
    pub fn LoadExternal(&self, req: TPM2_LoadExternal_REQUEST) -> LoadExternalResponse {
        unimplemented!();
    }
    pub fn ReadPublic(&self, req: TPM2_ReadPublic_REQUEST) -> ReadPublicResponse {
        unimplemented!();
    }
    pub fn ActivateCredential(&self, req: TPM2_ActivateCredential_REQUEST) -> ActivateCredentialResponse {
        unimplemented!();
    }
    pub fn MakeCredential(&self, req: TPM2_MakeCredential_REQUEST) -> MakeCredentialResponse {
        unimplemented!();
    }
    pub fn Unseal(&self, req: TPM2_Unseal_REQUEST) -> UnsealResponse {
        unimplemented!();
    }
    pub fn ObjectChangeAuth(&self, req: TPM2_ObjectChangeAuth_REQUEST) -> ObjectChangeAuthResponse {
        unimplemented!();
    }
    pub fn CreateLoaded(&self, req: TPM2_CreateLoaded_REQUEST) -> CreateLoadedResponse {
        unimplemented!();
    }
    pub fn Duplicate(&self, req: TPM2_Duplicate_REQUEST) -> DuplicateResponse {
        unimplemented!();
    }
    pub fn Rewrap(&self, req: TPM2_Rewrap_REQUEST) -> RewrapResponse {
        unimplemented!();
    }
    pub fn Import(&self, req: TPM2_Import_REQUEST) -> ImportResponse {
        unimplemented!();
    }
    pub fn RSA_Encrypt(&self, req: TPM2_RSA_Encrypt_REQUEST) -> RSA_EncryptResponse {
        unimplemented!();
    }
    pub fn RSA_Decrypt(&self, req: TPM2_RSA_Decrypt_REQUEST) -> RSA_DecryptResponse {
        unimplemented!();
    }
    pub fn ECDH_KeyGen(&self, req: TPM2_ECDH_KeyGen_REQUEST) -> ECDH_KeyGenResponse {
        unimplemented!();
    }
    pub fn ECDH_ZGen(&self, req: TPM2_ECDH_ZGen_REQUEST) -> ECDH_ZGenResponse {
        unimplemented!();
    }
    pub fn ECC_Parameters(&self, req: TPM2_ECC_Parameters_REQUEST) -> ECC_ParametersResponse {
        unimplemented!();
    }
    pub fn ZGen_2Phase(&self, req: TPM2_ZGen_2Phase_REQUEST) -> ZGen_2PhaseResponse {
        unimplemented!();
    }
    pub fn ECC_Encrypt(&self, req: TPM2_ECC_Encrypt_REQUEST) -> ECC_EncryptResponse {
        unimplemented!();
    }
    pub fn ECC_Decrypt(&self, req: TPM2_ECC_Decrypt_REQUEST) -> ECC_DecryptResponse {
        unimplemented!();
    }
    pub fn EncryptDecrypt(&self, req: TPM2_EncryptDecrypt_REQUEST) -> EncryptDecryptResponse {
        unimplemented!();
    }
    pub fn EncryptDecrypt2(&self, req: TPM2_EncryptDecrypt2_REQUEST) -> EncryptDecrypt2Response {
        unimplemented!();
    }
    pub fn Hash(&self, req: TPM2_Hash_REQUEST) -> HashResponse {
        unimplemented!();
    }
    pub fn HMAC(&self, req: TPM2_HMAC_REQUEST) -> HMACResponse {
        unimplemented!();
    }
    pub fn MAC(&self, req: TPM2_MAC_REQUEST) -> MACResponse {
        unimplemented!();
    }
    pub fn GetRandom(&self, req: TPM2_GetRandom_REQUEST) -> GetRandomResponse {
        unimplemented!();
    }
    pub fn StirRandom(&self, req: TPM2_StirRandom_REQUEST) -> StirRandomResponse {
        unimplemented!();
    }
    pub fn HMAC_Start(&self, req: TPM2_HMAC_Start_REQUEST) -> HMAC_StartResponse {
        unimplemented!();
    }
    pub fn MAC_Start(&self, req: TPM2_MAC_Start_REQUEST) -> MAC_StartResponse {
        unimplemented!();
    }
    pub fn HashSequenceStart(&self, req: TPM2_HashSequenceStart_REQUEST) -> HashSequenceStartResponse {
        unimplemented!();
    }
    pub fn SequenceUpdate(&self, req: TPM2_SequenceUpdate_REQUEST) -> SequenceUpdateResponse {
        unimplemented!();
    }
    pub fn SequenceComplete(&self, req: TPM2_SequenceComplete_REQUEST) -> SequenceCompleteResponse {
        unimplemented!();
    }
    pub fn EventSequenceComplete(&self, req: TPM2_EventSequenceComplete_REQUEST) -> EventSequenceCompleteResponse {
        unimplemented!();
    }
    pub fn Certify(&self, req: TPM2_Certify_REQUEST) -> CertifyResponse {
        unimplemented!();
    }
    pub fn CertifyCreation(&self, req: TPM2_CertifyCreation_REQUEST) -> CertifyCreationResponse {
        unimplemented!();
    }
    pub fn Quote(&self, req: TPM2_Quote_REQUEST) -> QuoteResponse {
        unimplemented!();
    }
    pub fn GetSessionAuditDigest(&self, req: TPM2_GetSessionAuditDigest_REQUEST) -> GetSessionAuditDigestResponse {
        unimplemented!();
    }
    pub fn GetCommandAuditDigest(&self, req: TPM2_GetCommandAuditDigest_REQUEST) -> GetCommandAuditDigestResponse {
        unimplemented!();
    }
    pub fn GetTime(&self, req: TPM2_GetTime_REQUEST) -> GetTimeResponse {
        unimplemented!();
    }
    pub fn CertifyX509(&self, req: TPM2_CertifyX509_REQUEST) -> CertifyX509Response {
        unimplemented!();
    }
    pub fn Commit(&self, req: TPM2_Commit_REQUEST) -> CommitResponse {
        unimplemented!();
    }
    pub fn EC_Ephemeral(&self, req: TPM2_EC_Ephemeral_REQUEST) -> EC_EphemeralResponse {
        unimplemented!();
    }
    pub fn VerifySignature(&self, req: TPM2_VerifySignature_REQUEST) -> VerifySignatureResponse {
        unimplemented!();
    }
    pub fn Sign(&self, req: TPM2_Sign_REQUEST) -> SignResponse {
        unimplemented!();
    }
    pub fn SetCommandCodeAuditStatus(&self, req: TPM2_SetCommandCodeAuditStatus_REQUEST) -> SetCommandCodeAuditStatusResponse {
        unimplemented!();
    }
    pub fn PCR_Extend(&self, req: TPM2_PCR_Extend_REQUEST) -> PCR_ExtendResponse {
        unimplemented!();
    }
    pub fn PCR_Event(&self, req: TPM2_PCR_Event_REQUEST) -> PCR_EventResponse {
        unimplemented!();
    }
    pub fn PCR_Read(&self, req: TPM2_PCR_Read_REQUEST) -> PCR_ReadResponse {
        unimplemented!();
    }
    pub fn PCR_Allocate(&self, req: TPM2_PCR_Allocate_REQUEST) -> PCR_AllocateResponse {
        unimplemented!();
    }
    pub fn PCR_SetAuthPolicy(&self, req: TPM2_PCR_SetAuthPolicy_REQUEST) -> PCR_SetAuthPolicyResponse {
        unimplemented!();
    }
    pub fn PCR_SetAuthValue(&self, req: TPM2_PCR_SetAuthValue_REQUEST) -> PCR_SetAuthValueResponse {
        unimplemented!();
    }
    pub fn PCR_Reset(&self, req: TPM2_PCR_Reset_REQUEST) -> PCR_ResetResponse {
        unimplemented!();
    }
    pub fn PolicySigned(&self, req: TPM2_PolicySigned_REQUEST) -> PolicySignedResponse {
        unimplemented!();
    }
    pub fn PolicySecret(&self, req: TPM2_PolicySecret_REQUEST) -> PolicySecretResponse {
        unimplemented!();
    }
    pub fn PolicyTicket(&self, req: TPM2_PolicyTicket_REQUEST) -> PolicyTicketResponse {
        unimplemented!();
    }
    pub fn PolicyOR(&self, req: TPM2_PolicyOR_REQUEST) -> PolicyORResponse {
        unimplemented!();
    }
    pub fn PolicyPCR(&self, req: TPM2_PolicyPCR_REQUEST) -> PolicyPCRResponse {
        unimplemented!();
    }
    pub fn PolicyLocality(&self, req: TPM2_PolicyLocality_REQUEST) -> PolicyLocalityResponse {
        unimplemented!();
    }
    pub fn PolicyNV(&self, req: TPM2_PolicyNV_REQUEST) -> PolicyNVResponse {
        unimplemented!();
    }
    pub fn PolicyCounterTimer(&self, req: TPM2_PolicyCounterTimer_REQUEST) -> PolicyCounterTimerResponse {
        unimplemented!();
    }
    pub fn PolicyCommandCode(&self, req: TPM2_PolicyCommandCode_REQUEST) -> PolicyCommandCodeResponse {
        unimplemented!();
    }
    pub fn PolicyPhysicalPresence(&self, req: TPM2_PolicyPhysicalPresence_REQUEST) -> PolicyPhysicalPresenceResponse {
        unimplemented!();
    }
    pub fn PolicyCpHash(&self, req: TPM2_PolicyCpHash_REQUEST) -> PolicyCpHashResponse {
        unimplemented!();
    }
    pub fn PolicyNameHash(&self, req: TPM2_PolicyNameHash_REQUEST) -> PolicyNameHashResponse {
        unimplemented!();
    }
    pub fn PolicyDuplicationSelect(&self, req: TPM2_PolicyDuplicationSelect_REQUEST) -> PolicyDuplicationSelectResponse {
        unimplemented!();
    }
    pub fn PolicyAuthorize(&self, req: TPM2_PolicyAuthorize_REQUEST) -> PolicyAuthorizeResponse {
        unimplemented!();
    }
    pub fn PolicyAuthValue(&self, req: TPM2_PolicyAuthValue_REQUEST) -> PolicyAuthValueResponse {
        unimplemented!();
    }
    pub fn PolicyPassword(&self, req: TPM2_PolicyPassword_REQUEST) -> PolicyPasswordResponse {
        unimplemented!();
    }
    pub fn PolicyGetDigest(&self, req: TPM2_PolicyGetDigest_REQUEST) -> PolicyGetDigestResponse {
        unimplemented!();
    }
    pub fn PolicyNvWritten(&self, req: TPM2_PolicyNvWritten_REQUEST) -> PolicyNvWrittenResponse {
        unimplemented!();
    }
    pub fn PolicyTemplate(&self, req: TPM2_PolicyTemplate_REQUEST) -> PolicyTemplateResponse {
        unimplemented!();
    }
    pub fn PolicyAuthorizeNV(&self, req: TPM2_PolicyAuthorizeNV_REQUEST) -> PolicyAuthorizeNVResponse {
        unimplemented!();
    }
    pub fn CreatePrimary(&self, req: TPM2_CreatePrimary_REQUEST) -> CreatePrimaryResponse {
        unimplemented!();
    }
    pub fn HierarchyControl(&self, req: TPM2_HierarchyControl_REQUEST) -> HierarchyControlResponse {
        unimplemented!();
    }
    pub fn SetPrimaryPolicy(&self, req: TPM2_SetPrimaryPolicy_REQUEST) -> SetPrimaryPolicyResponse {
        unimplemented!();
    }
    pub fn ChangePPS(&self, req: TPM2_ChangePPS_REQUEST) -> ChangePPSResponse {
        unimplemented!();
    }
    pub fn ChangeEPS(&self, req: TPM2_ChangeEPS_REQUEST) -> ChangeEPSResponse {
        unimplemented!();
    }
    pub fn Clear(&self, req: TPM2_Clear_REQUEST) -> ClearResponse {
        unimplemented!();
    }
    pub fn ClearControl(&self, req: TPM2_ClearControl_REQUEST) -> ClearControlResponse {
        unimplemented!();
    }
    pub fn HierarchyChangeAuth(&self, req: TPM2_HierarchyChangeAuth_REQUEST) -> HierarchyChangeAuthResponse {
        unimplemented!();
    }
    pub fn DictionaryAttackLockReset(&self, req: TPM2_DictionaryAttackLockReset_REQUEST) -> DictionaryAttackLockResetResponse {
        unimplemented!();
    }
    pub fn DictionaryAttackParameters(&self, req: TPM2_DictionaryAttackParameters_REQUEST) -> DictionaryAttackParametersResponse {
        unimplemented!();
    }
    pub fn PP_Commands(&self, req: TPM2_PP_Commands_REQUEST) -> PP_CommandsResponse {
        unimplemented!();
    }
    pub fn SetAlgorithmSet(&self, req: TPM2_SetAlgorithmSet_REQUEST) -> SetAlgorithmSetResponse {
        unimplemented!();
    }
    pub fn FieldUpgradeStart(&self, req: TPM2_FieldUpgradeStart_REQUEST) -> FieldUpgradeStartResponse {
        unimplemented!();
    }
    pub fn FieldUpgradeData(&self, req: TPM2_FieldUpgradeData_REQUEST) -> FieldUpgradeDataResponse {
        unimplemented!();
    }
    pub fn FirmwareRead(&self, req: TPM2_FirmwareRead_REQUEST) -> FirmwareReadResponse {
        unimplemented!();
    }
    pub fn ContextSave(&self, req: TPM2_ContextSave_REQUEST) -> ContextSaveResponse {
        unimplemented!();
    }
    pub fn ContextLoad(&self, req: TPM2_ContextLoad_REQUEST) -> ContextLoadResponse {
        unimplemented!();
    }
    pub fn FlushContext(&self, req: TPM2_FlushContext_REQUEST) -> FlushContextResponse {
        unimplemented!();
    }
    pub fn EvictControl(&self, req: TPM2_EvictControl_REQUEST) -> EvictControlResponse {
        unimplemented!();
    }
    pub fn ReadClock(&self, req: TPM2_ReadClock_REQUEST) -> ReadClockResponse {
        unimplemented!();
    }
    pub fn ClockSet(&self, req: TPM2_ClockSet_REQUEST) -> ClockSetResponse {
        unimplemented!();
    }
    pub fn ClockRateAdjust(&self, req: TPM2_ClockRateAdjust_REQUEST) -> ClockRateAdjustResponse {
        unimplemented!();
    }
    pub fn GetCapability(&self, req: TPM2_GetCapability_REQUEST) -> GetCapabilityResponse {
        unimplemented!();
    }
    pub fn TestParms(&self, req: TPM2_TestParms_REQUEST) -> TestParmsResponse {
        unimplemented!();
    }
    pub fn NV_DefineSpace(&self, req: TPM2_NV_DefineSpace_REQUEST) -> NV_DefineSpaceResponse {
        unimplemented!();
    }
    pub fn NV_UndefineSpace(&self, req: TPM2_NV_UndefineSpace_REQUEST) -> NV_UndefineSpaceResponse {
        unimplemented!();
    }
    pub fn NV_UndefineSpaceSpecial(&self, req: TPM2_NV_UndefineSpaceSpecial_REQUEST) -> NV_UndefineSpaceSpecialResponse {
        unimplemented!();
    }
    pub fn NV_ReadPublic(&self, req: TPM2_NV_ReadPublic_REQUEST) -> NV_ReadPublicResponse {
        unimplemented!();
    }
    pub fn NV_Write(&self, req: TPM2_NV_Write_REQUEST) -> NV_WriteResponse {
        unimplemented!();
    }
    pub fn NV_Increment(&self, req: TPM2_NV_Increment_REQUEST) -> NV_IncrementResponse {
        unimplemented!();
    }
    pub fn NV_Extend(&self, req: TPM2_NV_Extend_REQUEST) -> NV_ExtendResponse {
        unimplemented!();
    }
    pub fn NV_SetBits(&self, req: TPM2_NV_SetBits_REQUEST) -> NV_SetBitsResponse {
        unimplemented!();
    }
    pub fn NV_WriteLock(&self, req: TPM2_NV_WriteLock_REQUEST) -> NV_WriteLockResponse {
        unimplemented!();
    }
    pub fn NV_GlobalWriteLock(&self, req: TPM2_NV_GlobalWriteLock_REQUEST) -> NV_GlobalWriteLockResponse {
        unimplemented!();
    }
    pub fn NV_Read(&self, req: TPM2_NV_Read_REQUEST) -> NV_ReadResponse {
        unimplemented!();
    }
    pub fn NV_ReadLock(&self, req: TPM2_NV_ReadLock_REQUEST) -> NV_ReadLockResponse {
        unimplemented!();
    }
    pub fn NV_ChangeAuth(&self, req: TPM2_NV_ChangeAuth_REQUEST) -> NV_ChangeAuthResponse {
        unimplemented!();
    }
    pub fn NV_Certify(&self, req: TPM2_NV_Certify_REQUEST) -> NV_CertifyResponse {
        unimplemented!();
    }
    pub fn AC_GetCapability(&self, req: TPM2_AC_GetCapability_REQUEST) -> AC_GetCapabilityResponse {
        unimplemented!();
    }
    pub fn AC_Send(&self, req: TPM2_AC_Send_REQUEST) -> AC_SendResponse {
        unimplemented!();
    }
    pub fn Policy_AC_SendSelect(&self, req: TPM2_Policy_AC_SendSelect_REQUEST) -> Policy_AC_SendSelectResponse {
        unimplemented!();
    }
    pub fn ACT_SetTimeout(&self, req: TPM2_ACT_SetTimeout_REQUEST) -> ACT_SetTimeoutResponse {
        unimplemented!();
    }
    pub fn Vendor_TCG_Test(&self, req: TPM2_Vendor_TCG_Test_REQUEST) -> Vendor_TCG_TestResponse {
        unimplemented!();
    }
}
